[project]
name = "ai-ops"
version = "0.2.0"
description = "LLM-assisted penetration testing assistant"
requires-python = ">=3.12"

dependencies = [
    "bashlex>=0.18",
    "litellm>=1.84.0",
    "litellm[mlflow]",
    "mlflow>=3.11.1",
    "pydantic>=2.13",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
api = [
    "fastapi[standard]",
    "uvicorn",
    "httpx",
    "pydantic-settings"
]
dev = [
    { include-group = "api" },
    { include-group = "docs" },
    "pytest>=9.0.2",
    "pytest-asyncio",
    "pytest-cov",
    "isort",
    "pylint",
    "pandas>=2.2.2",
    "numpy",
    "matplotlib~=3.9.0",
    "seaborn~=0.13.2",
    "tqdm~=4.66.4",
    "transformers>=5.5.3",
    "streamlit>=1.40",
    "tokenizers",
    "ruff>=0.16.2",
    "pyinstrument"
]
bench = [
    "autopenbench"
]
docs = [
    "mkdocs>=1.6",
    "mkdocs-material>=9.5",
]

[tool.pytest.ini_options]
testpaths = ["test"]
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.uv.workspace]
exclude = [
    "benchmark/auto-pen-bench",
]

[tool.uv.sources]
autopenbench = { path = "benchmark/auto_pen_bench/auto-pen-bench", editable = true }

[tool.ruff.lint]
ignore = ["BLE001"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]

[tool.setuptools.packages.find]
include = ["ai_ops*"]
