name: "Unit Test"

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/unit-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENDPOINT: "http://127.0.0.1:11434"
    steps:
      -
        name: "Clone Repository"
        uses: "actions/checkout@v4"
        with:
          repository: "antoninoLorenzo/AI-OPS"
      -
        name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      -
        name: "Python Requirements"
        run: |
          pip install --upgrade pip
          pip install -r requirements-api.txt > /dev/null
          pip install -r requirements-dev.txt > /dev/null
          python -m spacy download en_core_web_md   > /dev/null
        shell: bash
      -
        name: "Run Unit Test"
        run: |
          # run unit testing
          echo "------------------------------------------------------------------------------------------------------"
          echo "-----------------------------------------Unit Test----------------------------------------------------"
          echo "------------------------------------------------------------------------------------------------------"
          python ./test/unit/runner.py
        shell: bash
